---
# backup for db

- name: Install MariaDB backup
  yum:
      name: MariaDB-backup, MySQL-python
      state: present
 
-  name: create backup user for MariaDB backup
   mysql_user:
      name: "{{ BACKUP_USER }}"
      password: "{{ BACKUP_USER_PASS }}"
      priv: "*.*:RELOAD,LOCK TABLES,PROCESS,REPLICATION CLIENT"
      state: present
   tags:
       - create_back_user
       
- name: create scripts in root home
  file:
      path: /root/scripts
      state: directory
      mode: 0755

- name: setup the backup DB script
  template:
      src: mariabackup.sh.j2
      dest: /root/scripts/mariabackup.sh
      mode: 0755

- name: setup the backup cron job
  cron:   
      name: "backup DB"
      minute: "0"
      hour: "2"
      job: "/root/scripts/mariabackup.sh --backup"
      
- name: setup the housekeep cron job
  cron:   
      name: "housekeep backup DB files"
      minute: "0"
      hour: "1"
      job: "/root/scripts/mariabackup.sh --housekeeper {{ USE_BACKUP }}"
